CROSS_COMPILE := mipsel-linux-gnu-
CFLAGS := -EL
LDFLAGS := -EL
SRCS := hello.c
INSTALL_APPS := build/hello:/bin/hello
INSTALL_APPS := hello.c:/home/hello.c

include $(ROOTFS_HOME)/Makefile.compile
include $(ROOTFS_HOME)/Makefile.app
